config/routes.rb
Jeopardy::Application.routes.draw do
  get "history" => "history#show"

  devise_for :users

  namespace :admin do
    resources :users do
      get :history
      get :analyze
    end
  end

  resources :games do
    resources :guesses
  end

  resources :challenges
  resource :leaderboard

  root :to => 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  has_many :plays
  has_many :games, :through => :plays
  has_many :single_player_games, :through => :plays
  has_many :multi_player_games, :through => :plays
  has_many :guesses
  has_many :challenges, :foreign_key => 'challengee_id'
  has_many :sent_challenges, :class_name => 'Challenge', :foreign_key => 'challenger_id'

  validates :username, :presence => true, :uniqueness => true
  validates :birthdate, :presence => true
  validates :city, :presence => true
  validates :state, :presence => true
  validates :country, :presence => true

  scope :online, where(:status => 'online')
  scope :with_total_scores, joins(:plays).group(:id).select('users.*, sum(score) as total_score')
  scope :active, where(:deleted_at => nil)

  def to_s
    username
  end

  def total_score
    plays.select('sum(score) as score').first.score
  end

  def username_with_score
    "#{username} (#{total_score} pts)"
  end

  def online?
    status == 'online'
  end

  def destroy
    update_attribute :deleted_at, Time.now
    challenges.destroy_all
    sent_challenges.destroy_all
  end

  def active?
    deleted_at.nil?
  end
  
  def wins
	plays.joins("inner join plays p2 on plays.game_id = p2.game_id and plays.id != p2.id").where("p2.score < plays.score")

  end
  def losses
	plays.joins("inner join plays p2 on plays.game_id = p2.game_id and plays.id != p2.id").where("p2.score > plays.score")

  end
  def draws 
	plays.joins("inner join plays p2 on plays.game_id = p2.game_id and plays.id != p2.id").where("p2.score = plays.score")
  end
  def top_three_letters 
	guesses.group("letter").order("count(letter) desc").limit(3).to_sentence
  end
	
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :authorize_admin!

  def index
    @users = User.active.order('username')
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      redirect_to admin_users_path
    else
      render :new
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    
    if params[:user][:password].blank? || params[:user][:password_confirmation].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    
    if @user.update_attributes(params[:user])
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  def history
    @user = User.find(params[:user_id])
  end
  
  def analyze
    @user = User.find(params[:user_id])
  end
  
  def destroy
    User.find(params[:id]).destroy
    
    redirect_to admin_users_path
  end

  def authorize_admin!
    unless current_user.admin?
      redirect_to root_path, :alert => 'You do not have permission to view that page.'
    end
  end
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div><%= f.label :username %><br />
  <%= f.text_field :username %></div>

  <div><%= f.label :birthdate %><br />
  <%= f.date_select :birthdate, :start_year => 1900 %></div>

  <div><%= f.label :city %><br />
  <%= f.text_field :city %></div>

  <div><%= f.label :state %><br />
  <%= f.text_field :state %></div>

  <div><%= f.label :country %><br />
  <%= f.text_field :country %></div>

  <div><%= f.label :email %><br />
  <%= f.email_field :email %></div>

  <% if @user.admin %>
    <div><%= f.label :name %><br />
    <%= f.text_field :name %></div>

    <div><%= f.label :phone %><br />
    <%= f.text_field :phone %></div>
  <% end %>

  <div><%= f.label :password %><br />
  <%= f.password_field :password %></div>

  <div><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></div>

  <div><%= f.submit %></div>
<% end -%>

app/views/admin/users/analyze.html.erb
<h1>Analyze <%= @user %></h1>
<ul>
<li>Total Score: <%=@user.total_score %></li>
<li>Number of Single Player Games: <%=@user.single_player_games.count %></li>
<li>Number of Multiplayer Games: <%=@user.multi_player_games.count %></li>
<li>Number of Wins: <%=@user.wins.count %></li>
<li>Number of Losses: <%=@user.losses.count %></li>
<li>Number of Draws: <%=@user.draws.count %></li>
<li>Top 3 Letters: <%=@user.top_three_letters %></li>
</ul>

app/views/admin/users/edit.html.erb
<h1>Edit user</h1>

<%= render 'form' %>

<%= link_to "Destroy this user", [:admin, @user], :confirm => 'Are you sure?', :method => :delete %>

app/views/admin/users/history.html.erb
<h1>History for <%= @user %></h1>
<ul>
<% @user.games.each do |game|%>
<li>
<%=game%>,
<strong>Points:</strong>
<%=game.play_for(@user).score%>
<%=link_to("details", game)%>
</li>
<% end -%>
</ul>

app/views/admin/users/index.html.erb
<h1>Manage Users</h1>

<table>
  <tr>
    <th></th>
    <th>Username</th>
    <th>Email</th>
    <th>Status</th>
  </tr>
  
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to "Edit", [:edit, :admin, user] %></td>
      <td><%= user.username %></td>
      <td><%= user.email %></td>
      <td><%= user.status %></td>
      <td><%= link_to "History", admin_user_history_path(user) %></td>
      <td><%= link_to "Analyze", admin_user_analyze_path(user) %></td>
      <% if ['online', 'in a game'].include? user.status %>
        <td><%= link_to "Logoff", admin_user_path(user, :user => {:status => 'kick_off'}), :method => :put %></td>
      <% end %>
    </tr>
  <% end %>
</table>

<%= link_to "Add user", new_admin_user_path %>

app/views/admin/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>