config/routes.rb
Jeopardy::Application.routes.draw do
  get "history" => "history#show"

  devise_for :users

  namespace :admin do
    resources :users do
      get :history
      get :analyze
    end
  end

  resources :games do
    resources :guesses
  end

  resources :challenges
  resource :leaderboard

  root :to => 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jeopardy</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <% if current_user %>
    <ul>
      <li><%= link_to "Home (#{current_user.games.reject(&:complete?).count} open games)", root_path %></li>
      <li><%= link_to "Edit profile", edit_user_registration_path %></li>
	  <li><%= link_to "History", history_path %></li>
      <li><%= link_to "New single-player game", games_path, :method => :post %></li>
      <li><%= link_to "New multi-player game", new_challenge_path %></li>
      <li><%= link_to "Challenges (#{current_user.challenges.count})", challenges_path %></li>
      <li><%= link_to "Leaderboard", leaderboard_path %></li>
      <% if current_user.admin? %>
        <li><%= link_to "Administrate users", admin_users_path %></li>
      <% end %>
      <li><%= link_to "Logout #{current_user}", destroy_user_session_path, :method => :delete %></li>
      <li>Your current status: <%= current_user.status %></li>
    </ul>
  <% end %>

<%= yield %>

</body>
</html>